# Generated by Django 5.2 on 2026-08-14 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='代码项目名称')),
                ('source_type', models.CharField(choices=[('zip_upload', 'zip_upload'), ('git_url', 'git_url')], default='zip_upload', max_length=20, verbose_name='来源类型')),
                ('git_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Git 地址')),
                ('repo_branch', models.CharField(blank=True, max_length=200, null=True, verbose_name='分支')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_code_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_projects', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'code_analysis_codeproject',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('commit_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commit 引用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('code_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='code_analysis.codeproject', verbose_name='代码项目')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_code_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'code_analysis_codeprojectsnapshot',
                'ordering': ['-created_at'],
                'unique_together': {('code_project', 'version_no')},
            },
        ),
        migrations.AddField(
            model_name='codeproject',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='code_analysis.codeprojectsnapshot', verbose_name='当前快照'),
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000, verbose_name='文件路径')),
                ('language', models.CharField(blank=True, default='', max_length=50, verbose_name='语言')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA256')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文件内容')),
                ('content_stored', models.BooleanField(default=False, verbose_name='内容已存储')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='code_analysis.codeprojectsnapshot', verbose_name='快照')),
            ],
            options={
                'db_table': 'code_analysis_codefile',
            },
        ),
        migrations.CreateModel(
            name='ComponentAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='状态')),
                ('file_filter', models.JSONField(blank=True, null=True, verbose_name='文件过滤')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='警告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('code_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_analysis_tasks', to='code_analysis.codeproject', verbose_name='代码项目')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_component_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_analysis_tasks', to='code_analysis.codeprojectsnapshot', verbose_name='快照')),
            ],
            options={
                'db_table': 'code_analysis_componentanalysistask',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('imported', 'imported')], default='pending', max_length=20, verbose_name='状态')),
                ('payload', models.JSONField(default=dict, verbose_name='建议内容')),
                ('imported_page_id', models.IntegerField(blank=True, null=True, verbose_name='导入的页面 ID')),
                ('imported_element_id', models.IntegerField(blank=True, null=True, verbose_name='导入的元素 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_suggestions', to='code_analysis.componentanalysistask', verbose_name='分析任务')),
            ],
            options={
                'db_table': 'code_analysis_elementsuggestion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='状态')),
                ('source', models.CharField(choices=[('upload', 'upload'), ('spec_url', 'spec_url')], default='upload', max_length=20, verbose_name='来源')),
                ('spec_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Spec 名称/URL')),
                ('use_llm', models.BooleanField(default=False, verbose_name='是否使用 LLM 增强')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='警告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('code_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_analysis_tasks', to='code_analysis.codeproject', verbose_name='代码项目')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spec_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'code_analysis_specanalysistask',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecAnalysisSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('imported', 'imported')], default='pending', max_length=20, verbose_name='状态')),
                ('payload', models.JSONField(default=dict, verbose_name='建议内容')),
                ('imported_interface_id', models.IntegerField(blank=True, null=True, verbose_name='导入的接口 ID')),
                ('imported_testcase_id', models.IntegerField(blank=True, null=True, verbose_name='导入的用例 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='code_analysis.specanalysistask', verbose_name='分析任务')),
            ],
            options={
                'db_table': 'code_analysis_specanalysissuggestion',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='codeproject',
            index=models.Index(fields=['project', '-created_at'], name='code_analys_project_d2ad63_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['snapshot', 'path'], name='code_analys_snapsho_4baeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['language'], name='code_analys_languag_24015a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codefile',
            unique_together={('snapshot', 'path')},
        ),
        migrations.AddIndex(
            model_name='componentanalysistask',
            index=models.Index(fields=['code_project', 'status'], name='code_analys_code_pr_860b98_idx'),
        ),
        migrations.AddIndex(
            model_name='elementsuggestion',
            index=models.Index(fields=['task', 'status'], name='code_analys_task_id_b59228_idx'),
        ),
        migrations.AddIndex(
            model_name='specanalysistask',
            index=models.Index(fields=['code_project', 'status'], name='code_analys_code_pr_41f7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='specanalysissuggestion',
            index=models.Index(fields=['task', 'status'], name='code_analys_task_id_8e87dd_idx'),
        ),
    ]
