# Generated by Django 5.2 on 2026-08-14 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0001_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文件路径')),
                ('testcase_type', models.CharField(choices=[('functional', 'functional'), ('api', 'api'), ('ui', 'ui')], max_length=20, verbose_name='用例类型')),
                ('testcase_id', models.IntegerField(verbose_name='用例 ID')),
                ('diff_status', models.CharField(choices=[('added', 'added'), ('modified', 'modified'), ('deleted', 'deleted')], max_length=20, verbose_name='变更类型')),
                ('old_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='旧 SHA256')),
                ('new_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='新 SHA256')),
                ('size_delta', models.IntegerField(blank=True, null=True, verbose_name='大小变化')),
                ('resolved', models.BooleanField(default=False, verbose_name='已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('code_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_impacts', to='code_analysis.codefile', verbose_name='代码文件')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_change_impacts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_impacts', to='code_analysis.codeprojectsnapshot', verbose_name='触发检测的快照')),
            ],
            options={
                'db_table': 'code_analysis_changeimpactrecord',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['snapshot', 'resolved'], name='code_analys_snapsho_916177_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestCodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_type', models.CharField(choices=[('functional', 'functional'), ('api', 'api'), ('ui', 'ui')], max_length=20, verbose_name='用例类型')),
                ('testcase_id', models.IntegerField(verbose_name='用例 ID')),
                ('path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文件路径')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True, verbose_name='符号/名称')),
                ('locator_ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='定位器引用')),
                ('status', models.CharField(choices=[('linked', 'linked'), ('outdated', 'outdated')], default='linked', max_length=20, verbose_name='状态')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最近校验时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_links', to='code_analysis.codefile', verbose_name='代码文件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_code_links', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_links', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'code_analysis_testcodelink',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', 'testcase_type', 'testcase_id'], name='code_analys_project_069e9b_idx'), models.Index(fields=['code_file'], name='code_analys_code_fi_f56672_idx')],
                'unique_together': {('project', 'testcase_type', 'testcase_id', 'path')},
            },
        ),
    ]
