# Generated by Django 5.2 on 2026-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0002_changeimpactrecord_testcodelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeimpactrecord',
            name='diff_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='行级差异摘要'),
        ),
    ]
