# Generated by Django 5.2 on 2026-08-14 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('langgraph_integration', '0027_chatsession_resolved_runtime_fields'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QaBatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='批次名称')),
                ('group', models.CharField(blank=True, default='', max_length=100, verbose_name='分组')),
                ('suite_ids', models.JSONField(blank=True, default=list, verbose_name='套件 ID 列表')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('partial', '部分通过'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='汇总')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_web_qa_batch_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_qa_batch_runs', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'web_qa_qabatchrun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QaSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('group', models.CharField(blank=True, default='', help_text='如 car_web', max_length=100, verbose_name='分组')),
                ('engine', models.CharField(choices=[('midscene', 'Midscene 视觉引擎'), ('agent_browser', 'agent-browser 语义引擎')], default='agent_browser', max_length=20, verbose_name='执行引擎')),
                ('base_url', models.CharField(blank=True, default='', max_length=500, verbose_name='基础 URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('yaml_content', models.TextField(blank=True, default='', verbose_name='YAML 脚本')),
                ('source', models.CharField(choices=[('manual', '手动创建'), ('prd_generated', 'PRD 生成')], default='manual', max_length=20, verbose_name='来源')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('generating', '生成中')], default='draft', max_length=20, verbose_name='状态')),
                ('test_count', models.IntegerField(default=0, verbose_name='用例数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_web_qa_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_qa_suites', to='langgraph_integration.llmconfig', verbose_name='LLM 配置')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_qa_suites', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'web_qa_qasuite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QaRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='汇总')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='结果 JSON')),
                ('report_md', models.TextField(blank=True, default='', verbose_name='Markdown 报告')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='web_qa.qabatchrun', verbose_name='所属批次')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_web_qa_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='web_qa.qasuite', verbose_name='套件')),
            ],
            options={
                'db_table': 'web_qa_qarun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLocatorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default='', max_length=500, verbose_name='基础 URL')),
                ('description_hash', models.CharField(max_length=64, verbose_name='描述哈希')),
                ('description', models.TextField(verbose_name='自然语言描述')),
                ('selector', models.CharField(max_length=500, verbose_name='缓存选择器')),
                ('strategy', models.CharField(choices=[('llm', 'LLM 视觉定位'), ('find', 'agent-browser find'), ('dom', 'DOM/快照降级')], default='llm', max_length=20, verbose_name='定位策略')),
                ('hits', models.IntegerField(default=0, verbose_name='命中次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_qa_locator_cache', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'db_table': 'web_qa_agentlocatorcache',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'base_url', 'description_hash'), name='uniq_web_qa_locator_cache')],
            },
        ),
        migrations.CreateModel(
            name='QaStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_index', models.IntegerField(default=0, verbose_name='用例序号')),
                ('test_name', models.CharField(blank=True, default='', max_length=300, verbose_name='用例名称')),
                ('step_index', models.IntegerField(default=0, verbose_name='步骤序号')),
                ('action', models.CharField(blank=True, default='', max_length=300, verbose_name='动作')),
                ('status', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('skip', '跳过'), ('error', '错误')], default='pass', max_length=20, verbose_name='状态')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=500, verbose_name='截图路径')),
                ('locator_meta', models.JSONField(blank=True, default=dict, verbose_name='定位元信息')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='web_qa.qarun', verbose_name='执行')),
            ],
            options={
                'db_table': 'web_qa_qastepresult',
                'ordering': ['run_id', 'test_index', 'step_index'],
                'indexes': [models.Index(fields=['run', 'test_index', 'step_index'], name='web_qa_qast_run_id_8f04f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='qasuite',
            index=models.Index(fields=['project', 'group'], name='web_qa_qasu_project_c6bcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='qasuite',
            index=models.Index(fields=['project', '-created_at'], name='web_qa_qasu_project_e98487_idx'),
        ),
        migrations.AddIndex(
            model_name='qarun',
            index=models.Index(fields=['suite', '-created_at'], name='web_qa_qaru_suite_i_9cbaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='qarun',
            index=models.Index(fields=['batch', '-created_at'], name='web_qa_qaru_batch_i_190555_idx'),
        ),
    ]
