# Generated by Django 5.2 on 2026-08-14 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0022_alter_testcasestep_expected_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(blank=True, help_text='对应的 TestCaseResult.id，非节点事件为空', null=True, verbose_name='用例结果ID')),
                ('event_type', models.CharField(max_length=40, verbose_name='事件类型')),
                ('status', models.CharField(blank=True, default='', max_length=20, verbose_name='节点状态')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件负载')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='testcases.testexecution', verbose_name='测试执行')),
            ],
            options={
                'verbose_name': '执行事件日志',
                'verbose_name_plural': '执行事件日志',
                'db_table': 'execution_event_log',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['run', 'created_at'], name='exec_evt_run_created_idx')],
            },
        ),
    ]
