# Generated by Claude Code for multi-agent review pipeline

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('langgraph_integration', '0027_chatsession_resolved_runtime_fields'),
        ('orchestrator_integration', '0010_delete_agent_config'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReviewRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, verbose_name='会话ID')),
                ('thread_id', models.CharField(blank=True, max_length=255, verbose_name='线程ID')),
                ('test_case_id', models.IntegerField(blank=True, null=True, verbose_name='关联测试用例ID')),
                ('mode', models.CharField(choices=[('single', '单 Agent 模式'), ('multi_review', '多 Agent 审查模式')], default='multi_review', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('reviewing', '审查中'), ('repairing', '修复中'), ('passed', '审查通过'), ('repaired', '已修复'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20)),
                ('thresholds', models.JSONField(blank=True, default=dict, verbose_name='审查阈值')),
                ('generation_snapshot', models.JSONField(blank=True, default=dict, verbose_name='生成阶段快照')),
                ('review_results', models.JSONField(blank=True, default=list, verbose_name='审查结果')),
                ('aggregate_score', models.FloatField(default=0, verbose_name='综合质量分')),
                ('aggregate_confidence', models.FloatField(default=0, verbose_name='综合置信度')),
                ('needs_repair', models.BooleanField(default=False, verbose_name='是否需要修复')),
                ('route_reason', models.TextField(blank=True, verbose_name='路由原因')),
                ('repair_prompt', models.TextField(blank=True, verbose_name='修复提示词')),
                ('repair_result', models.TextField(blank=True, verbose_name='修复结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_runs', to='langgraph_integration.chatsession', verbose_name='关联对话会话')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_review_runs', to='projects.project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_review_runs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent 审查记录',
                'verbose_name_plural': 'Agent 审查记录',
                'db_table': 'agent_review_run',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='agent_revie_user_id_59a1ec_idx'),
                    models.Index(fields=['project', 'created_at'], name='agent_revie_project_3411f0_idx'),
                    models.Index(fields=['session_id'], name='agent_revie_session_8d2230_idx'),
                ],
            },
        ),
    ]
